config/routes.rb
# Rails.application.routes.draw do
#   as :user do
#     put '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
#   end
#   devise_for :users, controllers: {
#     registrations: 'registrations', 
#     confirmation: 'confirmations'
#   }
#   # get 'home/index'
#   root "home#index"
# end

Rails.application.routes.draw do
   resources :projects
   resources :teams
  
 	as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end

  devise_for :users, controllers: {
  	registrations: 'registrations',
  	confirmations: 'confirmations'
  }

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @teams = Team.where('id = ?', current_user.team_id)
    @projects = Project.where('team_id = ?', current_user.team_id)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard.html.erb
<section class="section pt3">
	<p class="title is-5 border-bottom pb3 has-text-centered">Welcome <%= current_user.name %> 👋🏻</p>
	<div class="columns">

		<div class="column border-right ph4">
			<div class="level">
				<div class="level-left">
					<h3 class="subtitle is-5">My Projects <span class="tag is-rounded"><%= @projects.count %></span></h3>
				</div>
				<div class="level-right">
					<p class="field">
						<%= link_to new_project_path, class: 'button is-small' do %>
							<span class="icon is-small has-text-link"><i class="fa fa-plus"></i></span>
						<% end %>
					</p>
				</div>
			</div>
			<hr />
			<% @projects.each do |project|%>
				<div class="content border-bottom pb4">
					<p class="title is-4">
						<%= link_to project.name, project %>
					</p>
					<p class="subtitle is-6">
						<%= link_to project.team.name, project.team %>
					</p>
					<p class="f6">Created by: <%= project.user.name %></p>
				</div>
			<% end %>
		</div>
		

		<div class="column border-right ph4">
			<div class="level">
				<div class="level-left">
					<h3 class="subtitle is-5">My Teams <span class="tag is-rounded"><%= @teams.count %></span></h3>
				</div>
				<div class="level-right">
					<p class="field">
						<%= link_to new_team_path, class: 'button is-small' do %>
							<span class="icon is-small has-text-link"><i class="fa fa-plus"></i></span>
						<% end %>
					</p>
				</div>
			</div>
			<hr />
			<% @teams.each do |team|%>
				<div class="content border-bottom pb4">
					<p class="title is-4">
						<%= link_to team.name, team %>
					</p>
					<p class="subtitle is-6"><%= team.user.count %> Members</p>
					<span class="f6"><%= safe_join(team.users.map { |user| user.name}, ', ')%></span>
				</div>
			<% end %>	
		</div>

		<div class="column ph4">
			<h3 class="subtitle is-5">Activity</h3>
			<hr />
			<ul class="list">
				<li class="pv2 ph2 border-bottom">Activity Item</li>
			</ul>
		</div>
	
	</div>
</section>

app/views/home/_home.html.erb
<section class="hero is-link">
	<div class="hero-body">
		<div class="container has-text-centered">
			<h1 class="title">
				Welcome to Projekt
			</h1>
			<h2 class="subtitle">
				A small project management app built with Ruby on Rails
			</h2>
		</div>
	</div>
</section>
<section class="section">
	<div class="container">
		<div class="columns">
			<div class="column is-7">
				<div class="content">
					<h3 class="title is-3">Why is Projekt so awesome?</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum quo voluptatibus blanditiis quis odit rerum error laudantium quidem, est tenetur dolorum mollitia, molestiae quibusdam ipsam vero autem modi et nobis.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur, dignissimos nihil, impedit distinctio perspiciatis, soluta repellat expedita libero vitae ea debitis quae excepturi aperiam dolorem veritatis possimus, quos molestias molestiae.</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A quaerat, tempore qui! Veniam sequi adipisci aliquam rerum, quas laborum expedita, illum repellendus sunt sit necessitatibus minus quo assumenda provident numquam.</p>
				</div>
			</div>
			<div class="column is-4 is-offset1">
				<h4 class="subtitle is-4">Sign Up Today</h4>
				<%= link_to 'Sign Up', new_user_registration_path, class: 'button is-link is-outlined' %>
			</div>
		</div>
	</div>
</section>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<%= render 'dashboard' %>
	<% else %>
	<%= render 'home' %>
<% end %>